export const GET_CURRENT_TAB = 'GET_CURRENT_TAB'

export const GET_CONTACTS = 'GET_CONTACTS'

export const GET_CURRENT_CHATWITH_CONTACT = 'GET_CURRENT_CHATWITH_CONTACT'

export const GET_FUNCTION_CHOOSE_STATUS = 'GET_FUNCTION_CHOOSE_STATUS'

export const GET_CLIPBOARD_CONTENT = 'GET_CLIPBOARD_CONTENT'

export const GET_CURRENT_CHAT_LIST = 'GET_CURRENT_CHAT_LIST'

export const GET_ALL_CAHT_LIST = 'GET_ALL_CAHT_LIST'

export const GET_MESSAGES_LIST = 'GET_MESSAGES_LIST'

export const GET_LOGIN_USER = 'GET_LOGIN_USER'

export const GET_WHICH_AUDIO_PLAYING = 'GET_WHICH_AUDIO_PLAYING'

export const GET_PICTURE_VIEWER = 'GET_PICTURE_VIEWER'
