export const SET_CONTACTS = 'SET_CONTACTS'

export const SET_CURRENT_TAB = 'SET_CURRENT_TAB'

export const SET_CURRENT_CHATWITH_CONTACT = 'SET_CURRENT_CHATWITH_CONTACT'

export const SET_FUNCTION_CHOOSE_STATUS = 'SET_FUNCTION_CHOOSE_STATUS'

export const SAVE_MESSAGE = 'SAVE_MESSAGE'

export const DELETE_SINGLE_MESSAGE = 'DELETE_SINGLE_MESSAGE'

export const SET_MULTICHOOSE_STATUS = 'SET_MULTICHOOSE_STATUS'

export const TOGGLE_PICTURE_VIEWER_DISPLAY = 'TOGGLE_PICTURE_VIEWER_DISPLAY'

export const SET_WHICH_AUIDO_PLAYING = 'SET_WHICH_AUIDO_PLAYING'

export const TOGGLE_VIDEO_VIEWER_DISPLAY = 'TOGGLE_VIDEO_VIEWER_DISPLAY'

export const TOGGLE_AUDIO_VIEWER_DISPLAY = 'TOGGLE_AUDIO_VIEWER_DISPLAY'

export const TOGGLE_TEXT_VIEWER_DISPLAY = 'TOGGLE_TEXT_VIEWER_DISPLAY'


